# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT backend.api_server:app

runtime_config:
    operating_system: "ubuntu24"
    python_version: "3.14"

# [START handlers]
# Configure the runtime environment
env_variables:
  # Replace with your actual environment variables
  GEMINI_API_KEY: "AIzaSyCmfeU1MsmCvyfWdOPJI1TPtxPSdTGvkso"
  CLOUD_SQL_INSTANCE_CONNECTION_NAME: "alpine-dogfish-473616-j7:us-central1:mypgip"
  CLOUD_SQL_DB_USER: "sqlserver"
  CLOUD_SQL_DB_PASSWORD: "Akashsg@7422"
  CLOUD_SQL_DB_NAME: "Realestate"
  CLOUD_SQL_PRIVATE_IP: "false"  # Set to "true" if using private IP

# Configure the app's environment
service: default  # You can change this to a different service name if needed

# Configure the instance class. Default is F1 (free tier)
# For production, consider using F2 or higher
instance_class: F1

# Configure the number of instances
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

# Configure the resources
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Configure health checks
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 300  # Give the app time to start up

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300  # Give the app time to start up

# Configure the entrypoint
entrypoint: gunicorn -b :$PORT backend.api_server:app

# Configure the handlers
handlers:
  # Serve static files from the 'dist' directory
- url: /
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  redirect_http_response_code: 301

- url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff2|woff|ttf|eot|json))$
  static_files: dist/\1
  upload: dist/.*
  secure: always
  redirect_http_response_code: 301

# All other URLs should be handled by the Flask app
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
